initial commit
Mapanimal/mapanimal_frontend pull request #1
Opened 2022-02-08 18:07 UTC by Qarola

✔️ Created a skeleton to FE.

2022-02-12 18:23 UTC, gpgpublickey requested changes

2022-02-12 18:23 UTC, gpgpublickey commented on client/package.json
> +  "name": "client",
Please update the name to Mapanimal @Qarola

2022-02-12 18:23 UTC, gpgpublickey commented on client/public/manifest.json
> +  "short_name": "React App",
Please replace the name to Mapanimal

2022-02-12 18:23 UTC, gpgpublickey commented on client/src/App.js
> +          Learn React
Please create a task under the same story to make an "under construction landing page"

2022-02-12 18:23 UTC, gpgpublickey commented on client/src/index.css
> +body {
please move this file to a folder for styles

2022-02-12 18:23 UTC, gpgpublickey commented on client/src/redux/actions/index.js
> +//import axios from "axios";
Please remove it if it's not used, for now, leave commented code is a code smell.

2022-02-12 18:23 UTC, gpgpublickey commented on client/src/index.css
> +body {
consider translate to sass

2022-02-12 22:06 UTC, Qarola commented on client/src/redux/actions/index.js
> +//import axios from "axios";
If I remove it, the folder does not upload. I uploaded it to have some structure of all the folders to use. They may not all be used in sprint 0, but they are there.

2022-02-12 23:00 UTC, gpgpublickey commented on client/src/redux/actions/index.js
> +//import axios from "axios";
Ok @Qarola thx for the feedback

2022-02-12 23:01 UTC, gpgpublickey approved these changes

2022-02-12 23:01 UTC, gpgpublickey commented
@Qarola approved, ship it! (merge it)

2022-02-12 23:02 UTC, gpgpublickey approved these changes

2022-02-13 18:59 UTC, gpgpublickey commented
@dnlaMrno @JoanaRomay @Floriana19 @javierpz96   please approve if pass your review.

2022-02-19 20:18 UTC, merged