Readme/mapa 30 readme fe
Mapanimal/mapanimal_frontend pull request #2
Opened 2022-02-21 23:09 UTC by Qarola

✅ Creating a Readme file.

2022-02-22 01:48 UTC, Maarlopez approved these changes

2022-02-24 23:44 UTC, gpgpublickey requested changes

2022-02-24 23:44 UTC, gpgpublickey commented on README.md
> +## You can clone this repository following way:
You can clone this repository following way => You can clone this repository in following way:

2022-02-28 17:06 UTC, gpgpublickey approved these changes

2022-02-28 20:26 UTC, merged